name: 'Deploy'
on:
  push: 
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mortonprod/deployment-image:v0.0.3
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
      CLUSTER_NAME: kubernetes.alexandermorton.co.uk
      DELETE: no
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        with: 
          submodules: true
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
      - run: |
          pwd
          ls
          export KOPS_STATE_STORE=s3://state.${CLUSTER_NAME}
          if [[ ! $(kops get cluster --name "$CLUSTER_NAME") ]]; then
            echo "Build Cluster"
            kops create -f ${CLUSTER_NAME}.yaml --name "$CLUSTER_NAME" -v 10
            kops create secret sshpublickey admin -i $SSH_KEY
          else
            echo "Update Cluster"
            kops update cluster --yes
          fi
          # If we specify delete then do all our updating and then delete
          if [[ $DELETE == "yes" ]]; then
            kops delete cluster $CLUSTER_NAME
          fi

