name: 'Deploy'
on:
  push: 
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mortonprod/deployment-image:v0.0.3
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2
      CLUSTER_NAME: kubernetes.alexandermorton.co.uk
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DELETE: yes
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
        with: 
          submodules: true
          token: ${{ secrets.GITHUB_REPO_TOKEN }}
      - run: |
          export KOPS_STATE_STORE=s3://state.${CLUSTER_NAME}
          if [[ $DELETE == "no" ]]; then
            if [[ ! $(kops get cluster --name "$CLUSTER_NAME") ]]; then
              echo "Build Cluster"
              kops create -f ${CLUSTER_NAME}.yaml --name "$CLUSTER_NAME" -v 10
              mkdir ~/.ssh/
              echo $SSH_KEY >> ~/.ssh/id_rsa.pub
              echo $SSH_KEY | kops create --name "$CLUSTER_NAME" secret sshpublickey admin -i ~/.ssh/id_rsa.pub
              kops update cluster --name $CLUSTER_NAME --yes
              kops rolling-update cluster --yes
            else
              echo "Update Cluster"
              kops replace --force -f "${CLUSTER_NAME}.yaml"
              kops update cluster --name $CLUSTER_NAME --yes
              kops rolling-update cluster --yes
            fi
          else
            kops delete cluster $CLUSTER_NAME --yes
          fi

